version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: opsdesk-api
    command: pnpm start:dev
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - opsdesk

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: opsdesk-worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - opsdesk

  postgres:
    image: postgres:16
    container_name: opsdesk-postgres
    environment:
      POSTGRES_DB: opsdesk
      POSTGRES_USER: opsdesk
      POSTGRES_PASSWORD: opsdesk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opsdesk

  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_DB: opsdesk_test
      POSTGRES_USER: opsdesk
      POSTGRES_PASSWORD: opsdesk
    ports:
      - "5433:5432"
  
  redis:
    image: redis:7
    container_name: opsdesk-redis
    ports:
      - "6379:6379"
    networks:
      - opsdesk

  prometheus:
    image: prom/prometheus:latest
    container_name: opsdesk-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - opsdesk

  grafana:
    image: grafana/grafana:latest
    container_name: opsdesk-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - opsdesk

  rabbitmq:
    image: rabbitmq:3-management
    container_name: opsdesk-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - opsdesk

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: opsdesk-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - opsdesk

volumes:
  postgres_data:
  rabbitmq_data:
  grafana_data:

networks:
  opsdesk: